### PR TITLE
Observation

### PR DESCRIPTION
**Pull request by rhysm94**
An initial attempt at adding Observation to TCACoordinators

I've updated all the sample code to use the `@Reducer` macro, and for the screen reducers, I've migrated them to `@Reducer(state: .equatable)` where appropriate. This has reduced the amount of code needed to maintain these features, and they seems to work as before! I've even updated the UIKit example to use Observation.

This particular iteration of the work separates out the ObservedTCARouter from the normal TCARouter, but I think your patch should still be applicable over this work!

Also, just to note - there's a bit of additional work going on in the GameCoordinator that I'm not sure is super necessary. I think the entire GameCoordinator can probably be pared back so the `AppCoordinatorView` literally just switches between `GameView` and `LogInCoordinatorView` – what do you think?

### CODE REVIEW

**Comment by johnpatrickmorgan** [comment]
Thanks so much @rhysm94 ! I love how much this simplifies Screen reducers! 😍 I'll add my patch on top and update the README...

**Comment by johnpatrickmorgan** [comment]
I think these changes are good to merge if you're happy with the additions I've made?

**Comment by rhysm94** [comment]
> I think these changes are good to merge if you're happy with the additions I've made @rhysm94?

Super happy! Really love the way you got both ways working with the main `TCARouter`!

**Comment by rhysm94** [comment]
Ah, what happened to bump TCA to 1.8 specifically?

**Comment by johnpatrickmorgan** [comment]
> Ah, what happened to bump TCA to 1.8 specifically?
> 
> Wait, I'm a dope. It's the enum reducers! I think it's definitely worth keeping pinned to 1.8 as a minimum for that, as it provides such a huge ergonomic jump.

Yep, that's right, I agree, it's so much nicer!

**Comment by johnpatrickmorgan** [comment]
Thanks so much @rhysm94, this is such a great improvement! This has now been merged and shipped as [v0.10.0](https://github.com/johnpatrickmorgan/TCACoordinators/releases/tag/0.10.0).

**Pull request merged**
