### PR TITLE
Update for TCA Release 1.0

### PR DESCRIPTION
**Pull request by rhysm94**
I've made a number of changes in this PR, but basically all of them are for the sake of making TCACoordinators compatible with the release/1.0 branch of Composable Architecture.

Mostly, this required a number of deletions and renames.

Anything based on `AnyReducer` has been removed in release/1.0, so I've deleted all of the deprecated `AnyReducer`-based API.

`Effect+routeWithDelaysIfUnsupported` was previously based on Combine, which obviously still works in TCA 1.0 - but I thought this was a good opportunity to switch it to structured concurrency. If you'd rather keep this on Combine, I can revert this change, and use `Effect.publisher` instead!
One thing I did notice when updating this - the way the previous code works (and therefore, the way I've re-implemented it) is that `screens[0]` emits, and then (if present) `screens[1]` emits straight after, with `screens[2]` being delayed by 0.65 seconds. Is this expected, or should `screens[1]` also be delayed from emitting?

I did try removing the `ScreenState` and `ScreenAction` generics when working on the `ForEach` reducers, replacing them with references to `ScreenReducer.State` and `ScreenReducer.Action` respectively. However, it seems the Swift compiler fails to infer the end reducer type correctly, so I guess that'll have to wait 😅

I've tested this in a project which uses both `ForEachIdentifiedRoute` and `ForEachIndexedRoute`, and both still seem to work correctly (after updating *that* project to TCA 1.0).

I've also updated the example code to use newer syntax where appropriate - functions that returned an `Effect` are now `async` and performed inside an `Effect.run`, `ViewStore` initialisers have `observe` arguments - or the `ViewStore` has entirely been removed if it wasn't observing any state.

Obviously I'm not expecting this PR to be merged until TCA 1.0 is official - but hopefully it can be here, ready, and usable as a branch for people looking at migrating to TCA's release/1.0 branch!

### CODE REVIEW

**Comment by johnpatrickmorgan** [comment]
Wow, thanks so much for doing this work @rhysm94 - it's greatly appreciated. All your changes look good. 🙏 

With a [small additional change](https://github.com/johnpatrickmorgan/TCACoordinators/commit/4981c9947dd7bfd1a6088ac2f0364d10a67ba655), these changes seem to be compatible with TCA v0.57.0, so they could potentially be released ahead of TCA v1.0.

**Comment by johnpatrickmorgan** [comment]
> One thing I did notice when updating this - the way the previous code works (and therefore, the way I've re-implemented it) is that screens[0] emits, and then (if present) screens[1] emits straight after, with screens[2] being delayed by 0.65 seconds. Is this expected, or should screens[1] also be delayed from emitting?

You're absolutely right, this is how it was implemented. At the time, my thinking was that the first step is replacing any changed screens and the second step is actually the first push/pop/present operation, both of which can be done without delay. But it's always bothered me a little bit that there are two actions dispatched immediately, so I'd be happy to omit the first step, though it probably makes sense to make that change in FlowStacks' `calculateSteps` function.

**Comment by rhysm94** [comment]
I'll leave making any change to that step change algorithm!

What timing, that 0.57.0, with prerelease/1.0 merged in, happened the very day I pushed this PR 😄
Definitely makes sense to get the one with 0.57.0-compatibility merged in, and then I can push a new PR re-removing the `Failure == Never` in anticipation of the 1.0 release in ? weeks/months time.

**Comment by rhysm94** [comment]
Well, turns out it was "a few days' time".
I think there's probably still value in having a version that's 0.57.0-compatible, and another immediately after (since it's all released now) that's 1.0-compatible. What do you think @johnpatrickmorgan?

**Comment by rhysm94** [comment]
> @rhysm94 Any way you update your origin branch to point to the 0.58 release? That would allow proper versioning of everything on the TCA side while transitioning into the 1.0 world.

If that's of use, I can pull in the additional changes from @johnpatrickmorgan's [tca-release/0.57.0 branch](https://github.com/johnpatrickmorgan/TCACoordinators/compare/tca-release/0.57.0), but I felt like there might not be much point since those changes already exist on that branch, and it could just be merged in first?

If you just need to get pre-1.0 code working, you're probably best pointing at `.package(url: https://github.com/johnpatrickmorgan/TCACoordinators, branch: "tca-release/0.57.0")` I think?

Lemme know what you want me to do - more than happy to accommodate whatever!

**Comment by jshier** [comment]
Ah, sorry, didn't realize there was a separate branch for that.

**Comment by jshier** [comment]
@rhysm94 Seems like moving everything to the real 1.0 release would be the next step for this PR, as I don't see any other transitionary releases from TCA.

**Comment by rhysm94** [comment]
> @rhysm94 Seems like moving everything to the real 1.0 release would be the next step for this PR, as I don't see any other transitionary releases from TCA.

That makes a lot of sense! 😅
I've updated my branch/PR so it's pointing at Composable Architecture 1.0.0 now

**Comment by johnpatrickmorgan** [comment]
Thanks both, I've just merged in these changes and made two releases. FlowStacks release `0.5.0` is compatible with TCA 0.57/0.58 and FlowStacks release `0.6.0` is compatible with TCA 1.0. Thanks again @rhysm94 - I really appreciate you taking the time to bring the library up-to-date!

**Comment by vexonius** [comment]
Thank you guys for keeping this lib up to date! My team appreciate it! Cheers

**Pull request merged**
